FROM node:18-alpine

WORKDIR /app
COPY package.json .
COPY vite.config.ts .
COPY tsconfig.json .
COPY index.html .

RUN npm install

COPY public ./public/
COPY src ./src/

EXPOSE 3000

CMD ["npm", "start"]